### PR TITLE
move dm_bind() and dm_add_tbl() to zzx-deprecated.R

### PR DESCRIPTION
**Pull request by TSchiefer**
and also list the man entries of the 2 functions under category "deprecated".

cf. https://github.com/cynkra/dm/pull/1275/files#r921139560

### CODE REVIEW

**Comment by krlmlr** [comment]
This now has conflicts.

**Comment by TSchiefer** [comment]
Resolved now

**Comment by TSchiefer** [comment]
or not...: do we want to keep dm_bind() in its own R-file after all?

**Comment by krlmlr** [comment]
At least the `_impl` might live separately?

**Comment by TSchiefer** [comment]
Of course, thanks, I missed that it's being used by `dm()` now.
I could move it to dm.R or leave it in bind.R if you prefer.
The rest of dm_bind would go again to zzx-deprecated.R

**Comment by krlmlr** [comment]
Still conflicted.

**Comment by TSchiefer** [comment]
was waiting for the answer to: "I could move it [dm_bind_impl()] to dm.R or leave it in bind.R if you prefer."

**Comment by krlmlr** [comment]
No preference.

**Comment by TSchiefer** [comment]
left `dm_bind_impl()` in bind.R to not overload dm.R

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
