### PR TITLE
decompose and unite within 'dm'

### LINKED ISSUE #211: 'decompose_table()' and 'reunite_...'-funs -> work within 'dm'
new functions should be `dm_separate_tbl()`, `dm_unite_tbl()`

### PR DESCRIPTION
**Pull request by TSchiefer**
- function `dm_separate_tbl()` works like `decompose_table()` and takes care of key relations
- function `dm_unite_tbls()` works like `reunite_parent_child()` and takes care of FKs

fixes #211

### CODE REVIEW

**Comment by TSchiefer** [comment]
Is this roughly how it should be? (cf.tests)

**Comment by krlmlr** [comment]
Auto-styling is fixed in master.

**Comment by TSchiefer** [comment]
I decided to take another shot at this, as I think this functionality could be rather useful under certain circumstances.
I now left `decompose_table()`, `reunite_parent_child()` and `reunite_parent_child_from_list()` un-deprecated, since they might be nice for trying out stuff spontaneously. If they should be deprecated it's fine with me though.

**Comment by krlmlr** [comment]
Keeping as reference for now.

**Comment by krlmlr** [comment]
Closing for now, added a reference to the issue.

**Pull request closed without merging**
