### PR TITLE
Update tests for pillar 1.6.2

### PR DESCRIPTION
**Pull request by krlmlr**
How can we make these tests less brittle?

### CODE REVIEW

**Comment by TSchiefer** [comment]
Could it be that we also need this change in `tests/testthat/_snaps/examine-constraints.md`:
```r
# output as tibble

    Code
      dm_nycflights_small_cycle() %>% dm_examine_constraints() %>% as_tibble()
    Output
      # A tibble: 7 x 6
        table    kind  columns ref_table is_key problem
        <chr>    <chr> <keys>  <chr>     <lgl>  <chr>
      1 flights  FK    dest    airports  FALSE  "values of `flights$dest` not in `airp~
      2 flights  FK    tailnum planes    FALSE  "values of `flights$tailnum` not in `p~
      3 airlines PK    carrier <NA>      TRUE   ""
      4 airports PK    faa     <NA>      TRUE   ""
      5 planes   PK    tailnum <NA>      TRUE   ""
      6 flights  FK    carrier airlines  TRUE   ""
      7 flights  FK    origin  airports  TRUE   ""
```
replacing lines 32-46?

It seems that in main as well as in this PR some tests fail due to this (e.g. https://github.com/cynkra/dm/runs/3211670877)

**Comment by krlmlr** [comment]
Maybe. Would you like to take this on?

**Review by TSchiefer — APPROVED** [review]
LGTM

**Comment by krlmlr** [comment]
I love auto-merge!

**Pull request merged**
