### PR TITLE
feat: allow for additional description of tables in dm_draw()

### LINKED ISSUE #1875: Add comments to tables when drawing
Big organisations often have databases with a lot of cryptically named tables. There is a need for our client to be able to see a description of some tables in the `dm_draw()` output. I would imagine that setting comments would be similar to setting colors. Is that technically possible with DiagrammeR?

### PR DESCRIPTION
**Pull request by TSchiefer**
@moodymudskipper Could you please have a look?
We could make the font size for the description an additional argument.

``` r
suppressPackageStartupMessages(library(dm))

dm_nycflights13() |> dm_draw(table_description = c("flights" = "Flüge", "planes" = "Flugzeuge\navion\nel avión"))
```

``` r
dm_nycflights13() |> dm_draw(table_description = list("flights" = "Flüge", "planes" = "Flugzeuge\nl'avion\nel avión"))
```

<sup>Created on 2023-04-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

closes #1875

### CODE REVIEW

**Comment by TSchiefer** [comment]
regarding the custom function `repair_html()` from [7f12a71](https://github.com/cynkra/dm/pull/1876/commits/7f12a71c00354bac1faf783a310fa5b00508be99): there is `htmltools::htmlEscape()`, but for some reason it does not escape single and double quotes, which might lead to problems. 
Also one dependency less (even though it's already in "Suggests").

**Comment by TSchiefer** [comment]
@moodymudskipper do you prefer this?
dm_table_desc_V2

**Comment by moodymudskipper** [comment]
I like the last one (bottom) a lot, there was a bit too many colors on the original

**Comment by moodymudskipper** [comment]
Do you need me to review the code too, or are you comfortable with your changes there ?

**Comment by TSchiefer** [comment]
as discussed, this would be the newest version. Mind, that the white lines are visible also between the different column names.

``` r
library(dm)

dm_nycflights13(color = FALSE) %>% 
  dm_select_tbl(flights, starts_with("air"), weather) %>% 
  dm_select(flights, 9:19) %>%  
  dm_select(weather, c(1, 5,  10:15)) %>% 
  dm_set_colors("#AA3399" = flights, "#33AA99" = starts_with("air"), "#000000" = weather) %>% 
  dm_draw(
    table_description = c(
      "flights" = "high in the sky\nflying from NY", 
      "airports" = "gdsgblgd\ngds", 
      "weather" = "gelge"), 
    view_type = "all"
  )
```



<sup>Created on 2023-04-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

So that would be the advantage of choosing white as a BG-color: there we don't see those lines. But I still think the intermediate color (like in this reprex here) is nicer.
What's your opinion?

**Comment by TSchiefer** [comment]
Merging this now.
@krlmlr: I'm happy to discuss this later on and change the implementation, but it's beneficial to take it to main sooner rather than later.

**Pull request merged**
