### PR TITLE
no proactive checks for schema existence and tweak MSSQL-schema-code

### PR DESCRIPTION
**Pull request by TSchiefer**
partly addresses #672: the proactive checks for schema existence are abolished.

For listing schemas on MSSQL we also now avoid matching `schema owner id` to `user id`. I just ran into trouble here (`schema owner id` didn't exist in `user id` list and therefore schema wasn't listed, even though it existed). 
Now used 3054912 as a workaround, that schemas that exist by default for backward compatibility are filtered out.

### CODE REVIEW

**Comment by TSchiefer** [comment]
Test failures seem to be fairly independent of the changes in the PR

**Comment by krlmlr** [comment]
Thanks. How is this tested?

**Comment by TSchiefer** [comment]
> How is this tested?

I am not sure how to reach this state, that the principal_id for a schema is not available in the user_id list. Apparently it is possible, since I've come across it, but I haven't found a way yet to get there. I have tested it in this specific setting though, and it worked...

(sorry BTW for the closing of the PR, misclicked)

**Review by krlmlr — APPROVED** [review]
Thanks!

**Comment by krlmlr** [comment]
Please merge with a bullet point in the merge commit message.

**Pull request merged**
