### PR TITLE
migrated the updated fonts solution from https://github.com/cynkra/cy…

### PR DESCRIPTION
**Pull request by talpitoo**
…nkraweb/issues/662

NOTE: related to https://github.com/cynkra/cynkraweb/issues/662

### CODE REVIEW

**Comment by talpitoo** [comment]
@christophsax @maelle please see my other comment here https://github.com/cynkra/cynkratemplate/pull/52#issuecomment-1971718352

**Comment by maelle** [comment]
So, building this locally I can't see the text on the cheatsheet. Did the links to the files change in the meantime?

image


Steps

- `install.packages("pkgdown")`
- `install.packages("pak")`
- `install.packages("servr")`
- `pak::pak()`
- `devtools::install()`
- `pkgdown::build_site()`
- `servr::httw("docs")`

**Comment by talpitoo** [comment]
@maelle i don't know where those links are coming from. This PR contains only 3 `.woff2` URLs, e.g. https://cynkra.com/assets/css/fonts/1449009/b3ca2df2-7bee-4fc0-84cb-b029b99c3b61.woff2 but your screenshot points to S3. I am not aware of the deeper architecture or cross-referencing other repos, e.g. cynkratemplate if plays a role or not. Maybe it will be okay on production and the S3 URLs appear on local builds only? cc. @christophsax

**Comment by krlmlr** [comment]
Maëlle, can you please work with @talpitoo to resolve this?

**Comment by maelle** [comment]
Currently building the pkgdown website locally.

**Comment by maelle** [comment]
still getting this

image

**Comment by krlmlr** [comment]
`docs-*` branch?

**Comment by maelle** [comment]
I contacted devops via mattermost

**Comment by maelle** [comment]
will open a new pr with a docs- branch

**Comment by maelle** [comment]
#2233

**Pull request closed without merging**
