### PR TITLE
migrated the updated fonts solution from https://github.com/cynkra/cy…

### PR DESCRIPTION
**Pull request by maelle**
…nkraweb/issues/662

Same as #2199 but branch name allowing a preview thanks @krlmlr

### CODE REVIEW

**Comment by krlmlr** [comment]
@wael-sadek: Can you please help here? I have retriggered the job to refresh the deployment.

**Comment by krlmlr** [comment]
Do we still need this PR?

**Comment by maelle** [comment]
yes I mean the preview is good so it should be merged

**Comment by krlmlr** [comment]
I applied be56e07bf to the `docs` branch which bases directly off of v1.0.10 . The changes should be available on the _main_ page after that.

Did you check main or /dev? The current preview doesn't show a difference, but the nightly build likely wiped the build from this PR.

Anyway, we'll see after https://github.com/cynkra/dm/actions/runs/11008275866 .

**Comment by krlmlr** [comment]
All seems good to me. Merging manually, thanks!

**Comment by maelle** [comment]
Thank you!

**Pull request closed without merging**
