### PR TITLE
extend dm_examine_constraints()

### PR DESCRIPTION
**Pull request by moodymudskipper**
This is the first squashed commit split from https://github.com/cynkra/dm/pull/571

### CODE REVIEW

**Comment by krlmlr** [comment]
Can you please resolve the conflicts?

**Comment by krlmlr** [comment]
It might be worthwhile to enable the `rerere` option before doing so, if there is a chance that the same conflict reappears elsewhere: `git config rerere.enabled true` . (The option is harmless otherwise.) I also use `git config merge.conflictStyle diff3` .

**Comment by krlmlr** [comment]
(The web UI isn't really helpful for this particular conflict.)

**Comment by moodymudskipper** [comment]
I think I messed up the squash, the new_repair_plan function ended up in the other commit and is required here...

**Comment by moodymudskipper** [comment]
@krlmlr I get this error on duckDB and similar with every DBMS except for SQLite : 

> Error (test-foreign-keys.R:191:3): dm_enum_fk_candidates() works as intended?
> Error: Error: duckdb_execute_R: Failed to run query
> Error: Error: Conversion Error: Could not convert string 'a' to INT32
> Backtrace:
> 1. testthat::expect_identical(...)
> 24. dbplyr:::collect.tbl_sql(.)
> 26. dbplyr:::db_collect.DBIConnection(x$src$con, sql, n = n, warn_incomplete = warn_incomplete)
> 28. duckdb::dbSendQuery(con, sql)
> 29. duckdb:::.local(conn, statement, ...)
> 30. duckdb:::duckdb_result(...)
> 31. duckdb:::duckdb_execute(res)


Here is the test :

```
test_that("enum_fk_candidates() works properly", {
  # FIXME: COMPOUND: Test for tf_2 -> tf_3 and other combinations too
  expect_silent(
    expect_equivalent_why(
      enum_fk_candidates(zoomed_dm(), tf_1),
      dm_enum_fk_candidates(dm_for_filter(), tf_2, tf_1)
    )
  )
})
```

I'm not sure how to debug this, could you give me pointers ?

**Comment by krlmlr** [comment]
You can try `dbplyr:sql_render()` instead of `collect()` to review the generated SQL.

**Comment by krlmlr** [comment]
This now has a lot of conflicts, but could be salvaged by reimplementing?

**Comment by krlmlr** [comment]
Relevant for #4.

**Pull request closed without merging**
