### PR TITLE
use cynkratemplate

### LINKED ISSUE #1064: Use cynkratemplate

### PR DESCRIPTION
**Pull request by maelle**
Fix #1064

TODOs

- [ ] I find the logo a bit small so made a cynkratemplate PR https://github.com/cynkra/cynkratemplate/pull/21
- [ ] If I get write access to cynkratemplate I can make the PR from the cynkratemplate repo.
- [ ] cynkratemplate font issue https://github.com/cynkra/cynkratemplate/issues/22 (@pat-s could you help with this?)

After merging
- [ ] #1351
- [ ] #1352

### CODE REVIEW

**Comment by maelle** [comment]
cynkratemplate PR https://github.com/cynkra/cynkratemplate/pull/21

**Comment by maelle** [comment]
I don't see the right font in Firefox actually https://github.com/cynkra/cynkratemplate/issues/22

**Comment by pat-s** [comment]
You should now have write access.

**Comment by krlmlr** [comment]
Is this in main already?

**Pull request closed without merging**
