### PR TITLE
api: deprecate `rows_truncate()` and `dm_rows_truncate()` (#1031)

### LINKED ISSUE #1031: Remove or deprecate rows_truncate() and dm_rows_truncate()
These are DDL and require different permissions.

### PR DESCRIPTION
**Pull request by TSchiefer**
closes #1031

### CODE REVIEW

**Comment by TSchiefer** [comment]
unsure about 2 things (see https://github.com/cynkra/dm/pull/1323/files):
1. why snapshot results of dm_rows_update() are missing
2. how to deal with dm_rows_truncate() that calls sql_rows_truncate() that was also exported and that I deprecated now as well.

**Comment by krlmlr** [comment]
I'll deal with snapshots, this is an artifact of the automated update. We also need to deprecate `dm_rows_truncate()` .

**Comment by TSchiefer** [comment]
I believe it's already deprecated

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
