### PR TITLE
dm_examine_cardinalities()

### LINKED ISSUE #264: Check cardinality within dm?
We could have a function `dm_examine_cardinality(dm, child_table, parent_table)` that will return the cardinality of the relation (child_table would need to have an existing FK pointing to parent_table).

### PR DESCRIPTION
**Pull request by TSchiefer**
looks currently like this:
``` r
dm:::dm_examine_cardinalities(dm::dm_nycflights13())
#> • FK: flights$(`carrier`) -> airlines$(`carrier`): surjective mapping (child: 1 to n -> parent: 1)
#> • FK: flights$(`origin`) -> airports$(`faa`): generic mapping (child: 0 to n -> parent: 1)
#> • FK: flights$(`origin`, `time_hour`) -> weather$(`origin`, `time_hour`): generic mapping (child: 0 to n -> parent: 1)
#> • FK: flights$(`tailnum`) -> planes$(`tailnum`): Column (`tailnum`) of table `flights` not a subset of column (`tailnum`) of table `planes`.
#> ! Not all FK constraints satisfied, call `dm_examine_constraints()` for details.
```

<sup>Created on 2022-01-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

progress bar is not yet implemented.

closes #264

### CODE REVIEW

**Review by krlmlr — APPROVED** [review]
Thanks, very nice! What's blocking the progress bar?

**Comment by TSchiefer** [comment]
It's work in progress; wanted to see if this is moving in the right direction

**Comment by TSchiefer** [comment]
Would you know how I can test the progress bar? If I do a snapshot test (with `skip_if_ide()`) for a big dm with a few FKs, in the console the progress bar is shown, but not in a snapshot test or a reprex, e.g.:
``` r
suppressPackageStartupMessages({
  library(tibble)
  library(dplyr)
  library(dm)
})
a <- tibble(a_1 = 1:100000, a_2 = 100000:1); b <- tibble(b_1 = 100000:500, b_2 = 500:100000); c <- tibble(c_1 = 1000:100000)
test_dm <- dm(a, b, c) %>% dm_add_fk(b, c(b_1, b_2), a, c(a_2, a_1)) %>% dm_add_fk(c, c_1, b, b_1) %>% dm_add_fk(b, b_2, c, c_1) %>% dm_add_fk(c, c_1, a, a_2)

dm:::dm_examine_cardinalities(test_dm)
#> • FK: c$(`c_1`) -> a$(`a_2`): injective mapping (child: 0 or 1 -> parent: 1)
#> • FK: c$(`c_1`) -> b$(`b_1`): injective mapping (child: 0 or 1 -> parent: 1)
#> • FK: b$(`b_1`, `b_2`) -> a$(`a_2`, `a_1`): Columns (`b_1`, `b_2`) of table `b` not a subset of columns (`a_2`, `a_1`) of table `a`.
#> • FK: b$(`b_2`) -> c$(`c_1`): Column (`b_2`) of table `b` not a subset of column (`c_1`) of table `c`.
#> ! Not all FK constraints satisfied, call `dm_examine_constraints()` for details.
```

<sup>Created on 2022-01-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Review by krlmlr — APPROVED** [review]
Thanks! No need to test the progress bar here.

**Pull request merged**
